package dao.jpa;

import dao.StationDAO;
import model.RiverStation;
import model.RiverStationEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Project: Smart River Water Level Monitoring and Data Collection System
 * Day 14: Spring Data JPA & H2 Database Integration
 * Syllabus Unit: UNIT V - DAO Pattern, ORM Adapter, Spring @Component Bean
 *
 * Concrete StationDAO implementation backed by Spring Data JPA & H2.
 * Acts as an adapter bridging the existing domain DAO interface with the
 * Spring Data JpaRepository — zero raw SQL or JDBC code needed here.
 *
 * Design Patterns Demonstrated:
 *   - Adapter Pattern : adapts JpaRepository API to the StationDAO interface
 *   - Dependency Injection : @Autowired injects the JpaRepository Spring bean
 */
@Component
@Primary
public class StationJpaDAO implements StationDAO {

    private final RiverStationJpaRepository jpaRepository;

    @Autowired
    public StationJpaDAO(RiverStationJpaRepository jpaRepository) {
        this.jpaRepository = jpaRepository;
    }

    @Override
    public List<RiverStation> getAllStations() {
        // findAll() -> SELECT * FROM jpa_stations  (auto-generated by JPA)
        return jpaRepository.findAll()
                .stream()
                .map(RiverStationEntity::toDomain)
                .collect(Collectors.toList());
    }

    @Override
    public RiverStation getStationById(String stationId) {
        // findById() -> SELECT * FROM jpa_stations WHERE station_id = ?
        return jpaRepository.findById(stationId)
                .map(RiverStationEntity::toDomain)
                .orElse(null);
    }

    @Override
    public void saveStation(RiverStation station) {
        // save() -> INSERT or UPDATE (Hibernate decides based on entity state)
        jpaRepository.save(RiverStationEntity.fromDomain(station));
    }

    @Override
    public void saveAllStations(List<RiverStation> stations) {
        List<RiverStationEntity> entities = stations.stream()
                .map(RiverStationEntity::fromDomain)
                .collect(Collectors.toList());
        // saveAll() -> batch INSERT/UPDATE
        jpaRepository.saveAll(entities);
    }

    @Override
    public boolean existsById(String stationId) {
        // Derived query: existsByStationId() -> SELECT COUNT(*) > 0 WHERE station_id = ?
        return jpaRepository.existsByStationId(stationId);
    }

    @Override
    public String getStorageSource() {
        return "H2 Embedded Database via Spring Data JPA (jpa_stations table)";
    }
}
