package dao.jpa;

import model.WaterLevelRecordEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Project: Smart River Water Level Monitoring and Data Collection System
 * Day 14: Spring Data JPA & H2 Database Integration
 * Syllabus Unit: UNIT V - Spring Data JPA, Repository Pattern, JPQL Derived Queries
 *
 * Spring Data JPA repository for WaterLevelRecordEntity.
 * All CRUD methods are auto-generated by Spring Data at runtime.
 * Custom derived queries demonstrate the Spring Data method naming convention
 * which avoids manually writing any JPQL or SQL.
 */
@Repository
public interface WaterLevelRecordJpaRepository extends JpaRepository<WaterLevelRecordEntity, String> {

    /**
     * Derived query: finds all records whose stationLocation field contains a given station name/ID.
     * Spring Data JPA translates this to:
     *   SELECT * FROM jpa_readings WHERE station_location LIKE %?%
     */
    List<WaterLevelRecordEntity> findByStationLocationContaining(String stationIdentifier);

    /**
     * Derived query: filters records whose alertStatus begins with a prefix (e.g. "CRITICAL", "WARNING").
     * Spring Data JPA translates this to:
     *   SELECT * FROM jpa_readings WHERE alert_status LIKE ?%
     */
    List<WaterLevelRecordEntity> findByAlertStatusStartingWith(String prefix);

    /**
     * Derived query: fetch records by river name.
     * SELECT * FROM jpa_readings WHERE river_name = ?
     */
    List<WaterLevelRecordEntity> findByRiverName(String riverName);
}
